[tool.ruff]
# Target Python version
target-version = "py311"
line-length = 160

[tool.ruff.lint]
# E = pycodestyle errors, F = Pyflakes, I = isort (imports), B = bugbear
select = ["E", "F", "I", "B"]
ignore = []

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint.per-file-ignores]
# Ignore "useless expression" (B018) and "module level import" (E402) in notebooks
"*.ipynb" = ["B018", "E402"]
